version: '2.1'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 3s
      retries: 12
    volumes:
      - ./var/db-data:/var/lib/mysql
  web:
    build: .
    environment:
      JOB_WORKER_URL: "redis://redis:6379/0"
      RAILS_ENV: 'production'
    volumes:
      - .:/sakve
    ports:
      - "3000:3000"
    command: ./docker_start.sh
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  redis:
    image: 'redis:latest'
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "ping"]
      timeout: 2s
      retries: 10
