version: '2.1'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 3s
      retries: 12
  web:
    build: .
    volumes:
      - .:/sakve
    ports:
      - "3000:3000"
    command: ./docker_start.sh
    depends_on:
      db:
        condition: service_healthy
