production:
  adapter: mysql2
  host: <%= ENV['SAKVE_DEV_DB_HOST'] %>
  database: <%= ENV['SAKVE_PROD_DB_NAME'] %>
  username: <%= ENV['SAKVE_PROD_DB_USER'] %>
  password: <%= ENV['SAKVE_PROD_DB_PASS'] %>
  encoding: utf8
  pool: 3
  timeout: 5000

development:
  adapter: mysql2
  host: <%= ENV['SAKVE_DEV_DB_HOST'] %>
  database: <%= ENV['SAKVE_DEV_DB_NAME'] %>
  username: <%= ENV['SAKVE_DEV_DB_USER'] %>
  password: <%= ENV['SAKVE_DEV_DB_PASS'] %>
  encoding: utf8
  pool: 30
  timeout: 5000

test:
  adapter: mysql2
  host: <%= ENV['SAKVE_DEV_DB_HOST'] %>
  database: <%= ENV['SAKVE_TEST_DB_NAME'] %>
  username: <%= ENV['SAKVE_TEST_DB_USER'] %>
  password: <%= ENV['SAKVE_TEST_DB_PASS'] %>
  encoding: utf8
  pool: 3
  timeout: 5000