---
:verbose: <%= ENV['SAKVE_SIDEKIQ_VERBOSE'] %>
:daemon: <%= ENV['SAKVE_SIDEKIQ_DEAMON'] %>
:logfile: ./log/sidekiq.log
:pidfile: ./tmp/pids/sidekiq.pid
development:
  :logfile: ./log/sidekiq_dev.log
