mceinit_fileupload:
  mode: 'specific_textareas'
  editor_selector: 'mceFileupload'
  theme: 'advanced'
  theme_advanced_layout_manager: "SimpleLayout"
  theme_advanced_statusbar_location: "bottom"
  theme_advanced_toolbar_location: "top"
  theme_advanced_toolbar_align: "left"
  theme_advanced_resizing: true
  relative_urls: false
  convert_urls: false
  cleanup: true
  cleanup_on_startup: true
  convert_fonts_to_spans: true
  theme_advanced_resize_horizontal: false
  theme_advanced_buttons1: "formatselect,fontsizeselect,bold,italic,underline,forecolor,backcolor,|,justifyleft,justifycenter,justifyright,justifyfull,indent,outdent,|,bullist,numlist,|,link,unlink,cleanup"
  theme_advanced_buttons2: "undo,redo,|,tablecontrols,|,fupload,image,media,|,blockquote"
  theme_advanced_buttons3: ""
  plugins: "media,inlinepopups,safari,paste,advimage,table,fupload"
  extended_valid_elements: "iframe[src|width|height|name|align],img[class|src|flashvars|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name|obj|param|embed|scale|wmode|salign|style],embed[src|quality|scale|salign|wmode|bgcolor|width|height|name|align|type|pluginspage|flashvars],object[align<bottom?left?middle?right?top|archive|border|class|classid|codebase|codetype|data|declare|dir<ltr?rtl|height|hspace|id|lang|name|style|tabindex|title|type|usemap|vspace|width]"
mceinit_advance:
  mode: 'specific_textareas'
  editor_selector: 'mceAdvance'
  theme: 'advanced'
  theme_advanced_layout_manager: "SimpleLayout"
  theme_advanced_statusbar_location: "bottom"
  theme_advanced_toolbar_location: "top"
  theme_advanced_toolbar_align: "left"
  theme_advanced_resizing: true
  relative_urls: false
  convert_urls: false
  cleanup: true
  cleanup_on_startup: true
  convert_fonts_to_spans: true
  theme_advanced_resize_horizontal: false
  theme_advanced_buttons1: "formatselect,fontsizeselect,bold,italic,underline,forecolor,backcolor,|,justifyleft,justifycenter,justifyright,indent,outdent,|,bullist,numlist,|,link,unlink,cleanup"
  theme_advanced_buttons2: "undo,redo"
  theme_advanced_buttons3: ""
  plugins: "media,inlinepopups,safari,paste,advimage"
  extended_valid_elements: "iframe[src|width|height|name|align],img[class|src|flashvars|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name|obj|param|embed|scale|wmode|salign|style],embed[src|quality|scale|salign|wmode|bgcolor|width|height|name|align|type|pluginspage|flashvars],object[align<bottom?left?middle?right?top|archive|border|class|classid|codebase|codetype|data|declare|dir<ltr?rtl|height|hspace|id|lang|name|style|tabindex|title|type|usemap|vspace|width]"
mceinit_simple:
  mode: 'specific_textareas'
  editor_selector: 'mceSimple'
  theme: 'simple'
